from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from Business_app.models import Dataset, ColumnMapping
import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors

@login_required
def reports(request):

    dataset = Dataset.objects.filter(
        user=request.user,
        is_active=True
    ).first()

    if not dataset:

        return render(request, "reports.html", {
            "error": "No dataset uploaded."
        })

    mapping = ColumnMapping.objects.get(
        dataset=dataset
    )

    if dataset.file.name.endswith(".csv"):
        df = pd.read_csv(dataset.file.path)
    else:
        df = pd.read_excel(dataset.file.path)

    total_revenue = df[mapping.revenue_column].sum()

    total_sales = df[mapping.sales_column].sum()

    total_products = df[mapping.product_column].nunique()

    top_product = (
        df.groupby(mapping.product_column)[mapping.revenue_column]
        .sum()
        .idxmax()
    )

    context = {

        "dataset_name": dataset.name,

        "total_revenue": f"{total_revenue:,.0f}",

        "total_sales": total_sales,

        "total_products": total_products,

        "top_product": top_product,

    }

    return render(
        request,
        "reports.html",
        context
    )

@login_required
def download_report(request):

    dataset = Dataset.objects.filter(
        user=request.user,
        is_active=True
    ).first()

    if not dataset:
        return HttpResponse("No dataset found.")

    mapping = ColumnMapping.objects.get(dataset=dataset)

    if dataset.file.name.endswith(".csv"):
        df = pd.read_csv(dataset.file.path)
    else:
        df = pd.read_excel(dataset.file.path)

    total_revenue = df[mapping.revenue_column].sum()
    total_sales = df[mapping.sales_column].sum()
    total_products = df[mapping.product_column].nunique()

    top_product = (
        df.groupby(mapping.product_column)[mapping.revenue_column]
        .sum()
        .idxmax()
    )

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        'attachment; filename="Business_Report.pdf"'
    )

    doc = SimpleDocTemplate(response)

    styles = getSampleStyleSheet()
    report_date = datetime.now().strftime("%d-%m-%Y %I:%M %p")

    story = []

    # Title
    story.append(
        Paragraph(
            "AI Business Analytics Report",
            styles["Title"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["BodyText"])
    )

    # Date
    story.append(
        Paragraph(
            f"<b>Generated On:</b> {report_date}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["BodyText"])
    )

    data = [

        ["Metric", "Value"],

        ["Dataset", dataset.name],

        ["Total Revenue", f"Rs. {total_revenue:,.0f}"],

        ["Total Sales", total_sales],

        ["Total Products", total_products],

        ["Top Product", top_product],

    ]

    table = Table(
        data,
        colWidths=[180, 250]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TOPPADDING", (0, 1), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 8),

    ]))

    story.append(table)

    story.append(
        Paragraph("<br/><br/>", styles["BodyText"])
    )

    story.append(
        Paragraph(
            "<b>Business Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"""
            • The business generated a total revenue of
            <b>Rs. {total_revenue:,.0f}</b>.<br/><br/>

            • A total of <b>{total_sales}</b> units were sold across
            <b>{total_products}</b> unique products.<br/><br/>

            • The highest revenue-generating product is
            <b>{top_product}</b>.<br/><br/>

            • This report was automatically generated by the
            AI Business Analytics Platform.
            """,
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph("<br/><br/>", styles["BodyText"])
    )

    story.append(
        Paragraph(
            "<i>Generated by AI Business Analytics Platform</i>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return response

