# Generated by Django 6.0.6 on 2026-07-02 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_column', models.CharField(max_length=100)),
                ('sales_column', models.CharField(max_length=100)),
                ('product_column', models.CharField(max_length=100)),
                ('date_column', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Business_app.dataset')),
            ],
            options={
                'db_table': 'column_mapping',
            },
        ),
    ]
