# Generated by Django 6.0.6 on 2026-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_app', '0002_columnmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='category_column',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
